name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build
        shell: powershell
        run: dotnet build
      - name: Test
        shell: powershell
        run: dotnet test --filter Category!=Integration
